name: tests

on:
  push:
    branches:
      - master

  pull_request:

  schedule:
    - cron:  '*/5 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print the GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
